language: python
matrix:
  include:
  - os: linux
    dist: xenial
    python: 3.5
    env: TOXENV=py35
  - os: linux
    dist: xenial
    python: 3.6
    env: TOXENV=py36
  - os: linux
    dist: xenial
    python: 3.7
    env: TOXENV=py37,black,docs
  - os: osx
    language: generic
install:
- chmod +x .travis/install.sh
- "./.travis/install.sh"
script:
- chmod +x .travis/test.sh
- "./.travis/test.sh"
deploy:
  provider: pypi
  user: earthlab
  password:
    secure: EaWNpPWooWuP81EuBnBrIxVpfU5oL93WqhQmI3X2cGdvZtOukXrFY1407b1BahRSaTkNoRLBWXmJKiPT/9SBybXXi1H3Z/o2iJCtgEF9nJuXgMuciLQGNnHZKgIFvSpHKckGrjQa4RvvIa5P37KYIJ3lt/+WaChXLpQPuf3nMPeuhsLnPlabID6B3w6naRZOt+cU5DJT9QAllxtRbuZFgCfHQoG664zibeBX2Of01yadKvsnlS1HeTWhW87TY/inv6kwHNz4TnNZP9Gg4BvCDYlG16RtCWko4WVWujYFFS/7P4toLteCfAAdCUsLgDUbUcWo3wBkbfD6cjGIkOtGmkOJ7Sj69bxG2AEqEHBuaVdqhR7AjGvRHGjUpWYWKZ1PuWolYNabpmt/YvZjF+/Y+IwZ0fNzX/79n8tb58cFetwOpLmXS2N62YD1L6Vfl0ulh/lc/swwquLnH89d5u0w1iB3M68Pt0kCTmXtj5/XSIayR1Sa6oL7nuaTg8fzr3EQQewyTXWP7FUm0mneMwZBKSpSBmIbul9htVuwaZc+3I6RcXP0rsDNeBOe2jFEuGwRZ6LVzQCIl2pssn1eaWDD8RRzUBj3D0ZvfOqLMv2WJt1vcfm4mFRA9AHbozLigs9Zj+xRySfshBKHNz3VsrLoh7gIUYCuRjWYMDUSGgjQNEE=
  on:
    tags: true
    repo: earthlab/abc-classroom
    python: 3.6
